name: Deploy React Application

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  eslint:
    name: Linter ESLint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Install NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
      
      - name: Install dependencies
        run: npm install
      
      - name: Run ESLint
        run: npx eslint .

  build:
    name: Build Application
    runs-on: ubuntu-latest
    needs: eslint

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Install NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
      
      - name: Install dependencies
        run: npm i
      
      - name: Build project
        run: npm run build
      
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: production-files
          path: ./build

  deploy:
    name: Deploy Application
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: production-files
          path: ./build

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.ACTION_DEPLOY_KEY }}
          publish_dir: ./build